TEAM_NAME_MAPPING = {
    'NYY': 'New York Yankees"',
    'KCR': 'Kansas City Royals',
    'LAD': 'Los Angeles Dodgers',
    'BAL': 'Baltimore Orioles',
    'NYM': 'New York Mets',
    'BOS': 'Boston Red Sox',
    'CLE': 'Cleveland Guardians',
    'CIN': 'Cincinnati Reds',
    'ARI': 'Arizona Diamondbacks',
    'TOR': 'Toronto Blue Jays',
    'SFG': 'San Francisco Giants',
    'MIL': 'Milwaukee Brewers',
    'SEA': 'Seattle Mariners',
    'SDP': 'San Diego Padres',
    'HOU': 'Houston Astros',
    'PHI': 'Philadelphia Phillies',
    'OAK': 'Oakland Athletics',
    'ATL': 'Atlanta Braves',
    'TEX': 'Texas Rangers',
    'CHC': 'Chicago Cubs',
    'MIN': 'Minnesota Twins',
    'TBR': 'Tampa Bay Rays',
    'LAA': 'Los Angeles Angels',
    'DET': 'Detroit Tigers',
    'MIA': 'Miami Marlins',
    'STL': 'St. Louis Cardinals',
    'PIT': 'Pittsburgh Pirates',
    'COL': 'Colorado Rockies',
    'CHW': 'Chicago White Sox',
    'WSN': 'Washington Nationals'
}